### ISSUE TITLE
Add config param to allow install_command to be a no-op

### ISSUE THREAD

**Issue by j4m3s** [ahelal/kitchen-ansiblepush#18]
Would it be possible to add a config setting that can be used to prevent busser and chef from being installed on the target?  I'm using your kitchen plugin in combination with the kitchen-verifier-serverspec which runs the serverspec tests over ssh, so ruby isn't required at all on the server, let alone busser or chef.  

Combing your AnsiblePush plugin with @neillturner's kitchen-verifier-serverspec (in a ssh setup) has slashed build/test times compared to kitchen-ansible, and makes the tests much more valid (nothing is installed on the test hosts that won't be there when used against production servers).

**Comment by ahelal** [comment]
Hi @j4m3s it is already supported to disable installation of chef but poorly documented :( `:chef_bootstrap_url: nil`  https://github.com/ahelal/kitchen-ansiblepush/blob/master/lib/kitchen/provisioner/ansible_push.rb#L46

Hope that helps

**Comment by j4m3s** [comment]
Cracking, thank you.  I set chef_bootstrap_url to false in .kitchen.yml and it works like a charm :)
