### ISSUE TITLE
Does the 'groups' option do anything?

### ISSUE THREAD

**Issue by j4m3s** [ahelal/kitchen-ansiblepush#21]
Was looking at the readme and got curious about what the `groups` setting does different to the `mygroup'`setting.   And as far as I can see from my limited Ruby knowledge I don't think it does anything?

**Comment by ahelal** [comment]
Hey
Groups is used by inventory group. This is used ti create a group inventory https://github.com/ahelal/kitchen-ansiblepush/blob/master/bin/kitchen-ansible-inventory Could be useful if your trying  to orchestrate between groups

**Comment by j4m3s** [comment]
Ah sorry, I didn't think to look there.  Serves me right poking around in the code :)
