### ISSUE TITLE
tags & skip-tags does not work

### ISSUE THREAD

**Issue by crucifyhcy** [ahelal/kitchen-ansiblepush#41]
line 132 & line 133 should be like below
the single quote should be replaced by the double quote.

132         options << "--tags=#{as_list_argument(conf[:tags])}" if conf[:tags]
133         options << "--skip-tags=#{as_list_argument(conf[:skip_tags])}" if conf[:skip_tags]

or the vars will not be referred by the command.
please fix it.

**Comment by ahelal** [comment]
thank you 
fixed with 0.7.1 
https://github.com/ahelal/kitchen-ansiblepush/commit/6ea73169b758b580ea5c7d739a8c9c676a616b8b
