### ISSUE TITLE
Overriding inventory hostname?

### ISSUE THREAD

**Issue by con5cience** [ahelal/kitchen-ansiblepush#44]
Hi.

How do I override the inventory hostname set by the provisioner?

On https://github.com/ahelal/kitchen-ansiblepush/blob/master/lib/kitchen/provisioner/ansible_push.rb#L235 it looks like I should be able to do:

```
transport:
  connection_options:
    hostname: foo
```

But that doesn't work.

**Comment by thinkmassive** [comment]
I opened a PR that should implement this feature (which looks like it was previously conceived by @ahelal but not yet implemented). It will allow you the Ansible inventory name by defining the desired name as the value of `custom_instance_name` within the `provisioner` section.

**Comment by ahelal** [comment]
PR #45 merged. I will add more tests and do a release

**Comment by ahelal** [comment]
released with 0.8.0 
Thank you @thinkmassive
