### ISSUE TITLE
How to add single instance to inventory?

### ISSUE THREAD

**Issue by johnjelinek** [ahelal/kitchen-ansiblepush#47]
In my hosts inventory, I have a standalone server like this:
```
example ansible_host=somehost.example.com
```
it's not in a group -- how would I define this in `.kitchen.yml`?

**Comment by ahelal** [comment]
not sure what you mean. Since the default way to run kitchen-ansiblepush it will generate an inventory file.

**Comment by johnjelinek** [comment]
Yes, but how do you add arbitrary extra vars to a single inventory item or
to a host that isn't managed by Test kitchen (for integration tests)?

**Comment by ahelal** [comment]
Sorry again i am not following the use-case. If it is not managed by test-kitchen then what is the connection?.
If you can provide a repo ? or a more detailed use-case.

**Comment by johnjelinek** [comment]
I have a role and the role connects to an external server to download
binaries based on activity that happens from remote process execution. I
don't want to mock out that server to test my role, so that server needs to
be in the inventory that gets generated. Also, I need to set vars like
ansible_ssh_user to connect to it.

**Comment by ahelal** [comment]
Well i don't have a good answer, since I never had the need for such use case.
My best guess is one of either
1. Use the  **raw_arguments** and add `-i external.ini`  with your file and i think with the latest ansible you can kind of merge inventory

2. Maintain your inventory and not use the ansiblepush-kitchen dynamic inventory.

Good luck

**Comment by jmcmaster05** [comment]
**Raw Arguments Solution**
```
provisioner:
  name: ansible_push
  ...
  raw_arguments: "-i tests/inventory"
```
>[mygroup]
>server.domain.com

**Groups Solution** (thanks @johnjelinek )
```
provisioner:
  name: ansible_push
  ...
  groups:
    mygroup:
      - server.domain.com
```
