### ISSUE TITLE
how to add localhost as inventory file

### ISSUE THREAD

**Issue by bob2build** [ahelal/kitchen-ansiblepush#50]
kitchen-ansible-inventory does not include localhost. So I am unable to run any commands on the controller node. Is there any configuration to add localhost name in the inventory?
```bash
$ kitchen-ansible-inventory
{
  "all": [
    "default-bento-centos-74",
    "bento-centos-74"
  ],
  "_meta": {
    "hostvars": {
      "default-bento-centos-74": {
        "ansible_ssh_host": "127.0.0.1",
        "ansible_ssh_port": "2222",
        "ansible_ssh_private_key_file": "/Users/anmanoha/development/cloudtrust/ironhide/.kitchen/kitchen-vagrant/default-bento-centos-74/.vagrant/machines/default/virtualbox/private_key"
      },
      "bento-centos-74": {
        "ansible_ssh_host": "127.0.0.1",
        "ansible_ssh_port": "2222",
        "ansible_ssh_private_key_file": "/Users/anmanoha/development/cloudtrust/ironhide/.kitchen/kitchen-vagrant/default-bento-centos-74/.vagrant/machines/default/virtualbox/private_key"
      }
    }
  }
}
```

**Comment by ahelal** [comment]
you must use ansible `delegate_to: 127.0.0.1` and/or `connection=local`

**Comment by bob2build** [comment]
I didn't quite get how delegate_to: 127.0.0.1 works, 
I managed to make this work by creating a static file local_inventory.yaml in root directory
```yaml
all:
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: /usr/bin/python
```

and passed raw_arguments: "--inventory-file=test/ansible/local_inventory.yaml" in kitchen.yml

Thanks for the info @ahelal. This plugin works great. I infact use kitchen-ansiblepush to upload cookbooks tar.gz file to remove servers and run chef-solo. It is counter intuitive, however, kitchen is really slow to converge cookbooks since it uploads 1 file at a time.

**Comment by avishayil** [comment]
Hi @bob2build @ahelal Is this solution going to work with the internal inventory file that the plugin creates to connect to the created machine during converge?

**Comment by bob2build** [comment]
@avishayil I only tried with localhost. However, I believe this should allow you to add additional hosts on top of existing hosts created by vagrant.

**Comment by avishayil** [comment]
I'm working with kitchen ec2 driver, i'll try and let anyone know here in case someone else searches this. Thanks!
