### ISSUE TITLE
Work behind http proxy

### ISSUE THREAD

**Issue by avishayil** [ahelal/kitchen-ansiblepush#56]
Hi,
Can this plugin work when communication between ansible and remote host is behind http proxy (windows hosts)?

**Comment by ahelal** [comment]
Hi  avishayil,

the plugin uses Ansible so this is up to ansible to handle it. 
My best guess you need to set your environment "http_proxy". 
I am not sure how to achieve this in windows host, but I assume it is similar

**Comment by avishayil** [comment]
Hi @ahelal it works using psrp. I know the winrm gem supports it, is this library using the winrm gem?

**Comment by ahelal** [comment]
ansible-kitchen does not handle communication at all, it is left for `ansible` and `test-Kitchen`
