### ISSUE TITLE
Dependency on Omnibus_Chef still necessary?

### ISSUE THREAD

**Issue by Ari-E-S** [ahelal/kitchen-ansiblepush#7]
Hi, I'm currently using kitchen-ansible but kitchen-ansiblepush seems more appropriate if it weren't for its dependency on Chef.

I find in kitchen-ansible that they don't have it when using test-kitchen >= 1.4 and made installation optional:

> NOTE: With Test-Kitchen 1.4 you no longer need chef install to run the tests. You just need ruby installed version 1.9 or higher and also add to the .kitchen.yml file
> 
> provisioner:
>   name: ansible_playbook
>   hosts: test-kitchen
>   require_chef_for_busser: false
>   require_ruby_for_busser: true
> 
> verifier:
>   ruby_bindir: '/usr/bin'
> where /usr/bin is the location of the ruby command.

I wonder if this is also true for kitchen-ansiblepush

**Comment by ahelal** [comment]
Hi,

Well I did not have a chance to look into that yet, But you can disable installation of chef by adding `chef_bootstrap_url : fasle` to your **.kitchen.yml**
I am not sure if any extra work is needed. Let me know if it works. if not I will look into it when I have time

**Comment by Ari-E-S** [comment]
That worked beautifully.

Thanks!

**Comment by ahelal** [comment]
perect will close this issue. and in the next release will disable chef instalation by default
